# Indonesian site  
development:
  adapter: mysql2
  encoding: utf8
  database: abraresto
  username: root
  password: "120881"
  host: localhost
  pool: 24
  # socket: /Applications/MAMP/tmp/mysql/mysql.sock
  
production:
  adapter: mysql2
  encoding: utf8
  database: abraresto
  username: root
  password: "120881"
  socket: /var/lib/mysql/mysql.sock
  
staging: 
  adapter: mysql
  encoding: utf8
  database: abra_indo_staging
  username: wearelot_www
  password: REPLACE_WITH_PASSWORD
  socket: /var/lib/mysql/mysql.sock
