#= require jquery
#= require jquery_ujs
#= require bootstrap.min
#= require libs/masonry.pkgd.min
#= require libs/placeholders
#= require libs/jquery.magnific-popup.min
#= require libs/owl.carousel.min
#= require libs/respond.min
#= require libs/jquery.nested
#= require libs/mosaic
#= require libs/html5shiv
#= require libs/main
#= require libs/custom
#= require_self